image: ruby:2.4.2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - bundle install --frozen --deployment
    - bundle exec rake build
  tags:
    - docker
  artifacts:
    paths:
      - _config.yml
      - _site/

test:
  stage: test
  variables:
    LANG: C.UTF-8
  script:
#    - apt-get update && apt-get install -y locales
#    - locale-gen en_US.UTF-8 && 
#    - export LANG=en_US.UTF-8
#    - export LANGUAGE=en_US:en
#    - export LC_ALL=en_US.UTF-8
    - bundle install --frozen --deployment
    - bundle exec rake test
  tags:
    - docker

deploy:
  image: ubuntu:xenial
  stage: deploy
  script:
    - apt-get update && apt-get install -y ssh-client rsync && apt-get clean
    - echo "$DEPLOY_SSH_KEY" | base64 --decode > id_deploy && chmod 600 id_deploy
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_deploy" --progress _site/ ${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}:${DEPLOY_SSH_PATH}
  tags:
    - docker
  only:
    - master
