language: ruby
sudo: false
rvm:
  - 2.2.5
script:
  - bundle
  - rake test
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email: false
  irc:
    channels:
      - "irc.hackint.eu#ffka"
    use_notice: true
    on_success: change
    on_failure: always
#after_success:
#  - curl https://karlsruhe.freifunk.net/deploy
