# Site settings
title: Freifunk Karlsruhe
tagline: das freie WLAN-Netzwerk für KA und Umgebung
email: info@karlsruhe.freifunk.net
description: > # this means to ignore newlines until "baseurl:"
 Freifunk Karlsruhe ist eine lokale Initiative mit dem Ziel, ein WLAN-Netzwerk über Karlsruhe aufzuspannen und freien Internetzugang anzubieten.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karlsruhe.freifunk.net" # the base hostname & protocol for your site
twitter_username: FFKarlsruhe
github_username:  ffka

excerpt_separator: <!--*-->

permalink: "news/:year/:month/:day/:title"

# Build settings
markdown: kramdown
exclude: [vendor]
include: [.well-known]
